import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { client } from '../libs/client'

const Home: NextPage = ({ contents }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <ul>
            {contents.map((content: any) => (
              <li key={content.id}>
                <Link href={`/blog/${content.id}`}>
                  <a>{content.title}</a>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </div>
  )
}

// データをテンプレートに受け渡す部分の処理を記述します
export const getStaticProps = async () => {
  const data = await client.get({ endpoint: 'blogs' })

  return {
    props: {
      contents: data.contents,
    },
  }
}

export default Home
