import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { blogClient } from '../libs/blogClient'
import BlogCard from "../components/blogCard"
import { motion } from 'framer-motion'

const Home: NextPage = ({ contents }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <motion.div
          initial={{ opacity: 0 }} // 初期状態
          animate={{ opacity: 1 }} // マウント時
          exit={{ opacity: 0 }}    // アンマウント時
        >
          <div className="flex flex-wrap">
            {contents.map((content: any) => <BlogCard key={content.id} title={content.title} href={content.id} category={content.category} eyeCatch={content.eyecatch} tags={content.tag} />)}
          </div>
        </motion.div>
      </main>
    </div>
  )
}

// データをテンプレートに受け渡す部分の処理を記述します
export const getStaticProps = async () => {
  const data = await blogClient.get({ endpoint: 'blogs' })

  return {
    props: {
      contents: data.contents,
    },
  }
}

export default Home
